<a href="https://colab.research.google.com/github/TsIrDrPrakas/NumpyArray/blob/master/NumpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Numpy**

In [1]:
import numpy as np

Creating Array

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list = [[1,2],[3,4],[5,6]]

In [5]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

Creating automated array with stepsize

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Creating array with zeros (note the zeros are floating point numbers)

In [8]:
np.zeros(3)

array([0., 0., 0.])

Creating Matrix (Row, Column)

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Repeat above with ONES

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Linspace(star,end, num of elements)

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

Ones in diagonal

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random Array

In [17]:
np.random.rand(2)

array([0.38814215, 0.875833  ])

In [18]:
np.random.rand(3,4)

array([[0.10711833, 0.53118238, 0.16259283, 0.75768312],
       [0.01981636, 0.21414218, 0.18275281, 0.17597736],
       [0.57765346, 0.57507768, 0.28719681, 0.08030038]])

Random standart normal distribution

In [19]:
np.random.randn(5,5)

array([[-0.56845577,  0.68748766,  0.17090491, -0.76924982,  1.09469952],
       [-0.68912277,  0.40498659,  0.1986815 , -0.13803434,  1.96421982],
       [-2.16144963,  0.78291276, -0.30833963,  0.2266094 , -0.53573596],
       [ 1.20335898, -0.57132891,  1.80518973,  0.24577615, -0.58980043],
       [-0.58022462,  0.40241707,  0.63164813,  0.79212738, -1.25995303]])

Generates random integers using NumPy's randint function

In [21]:
np.random.randint(1,10)

3

In [22]:
np.random.randint(1,10,(2,3))

array([[9, 2, 2],
       [1, 3, 1]])

Sets the random seed to 42 using NumPy and generates an array of four random floats between 0 and 1 using rand()

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

NOTE: without seed np will generate random values

In [24]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

Creates a NumPy array 'arr' containing integers from 0 to 24 using arange().

In [28]:
arr =  np.arange(25)

Generates a NumPy array 'ranarr' with 10 random integers between 0 (inclusive) and 50 (exclusive) using randint().

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([ 1, 20, 32, 11, 21, 43, 24, 48, 26, 41])

Finding the shape

In [32]:
arr.shape

(25,)

Reshape

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

This does not change the original arr, calling arr to confirm

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

This is to permanently reshaping

In [36]:
arr = arr.reshape(5,5)

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Max, Min, and their location

In [38]:
ranarr.max()

48

In [39]:
ranarr.argmax()

7

In [40]:
ranarr.min()

1

In [41]:
ranarr.argmin ()

0

To find data type

In [43]:
ranarr.dtype

dtype('int64')